server:
  port: 9000
  
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  hateoas:
    use-hal-as-default-json-media-type: false
  
management:
  endpoints:
     web:
        exposure:
           include: 'metrics,prometheus'
     metrics:
        enabled: true
     prometheus:
        enabled: true
  metrics:
     export:
        prometheus:
           enabled: true


  
api:
  user: 'user'
  password: 'secret123'
  hostName: 'localhost'
  hostPort: '8080'
  hostScheme: 'http' 
  baseUrl: 'http://localhost:8080'
  airportsEndpoint: '/airports'
  fareEndPoint: '/fares'